# SCATTER PLOTS

In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
x=np.arange(10)
y1=x*x
y2=2*x+3
print(x)
print(y1)
print(y2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[ 3  5  7  9 11 13 15 17 19 21]


In [7]:
#Adjust the size of any plot
plt.figure(figsize=(2,2))

plt.scatter(x,y1,color='red',label='Apple',marker='o')
plt.scatter(x,y2,color='green',label='kiwi',marker='*')
plt.xlabel("time")
plt.ylabel("price")
plt.title("price of fruit over time")
plt.legend()
plt.show()